name: python-flask-app-CI

on:
    push:
        branches: [ main ]
    workflow_dispatch:

jobs:
    app-build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: set up python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"

            - name: install dependencies
              run: pip install -r requirements.txt

            - name: run app
              run: |
                python app.py &
                sleep 5
                curl http://localhost:5000

            - name: build docker image
              run: docker build -t url-status-api-app .

            - name: run docker container
              run: |
                docker run -d -p 5001:5000 --name url-status-api-container url-status-api-app
                sleep 5
                curl http://localhost:5001

